sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
    debug: true
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        jPXqPhTEwl3Vq6JyM2OZEUwGHJsoEQWdQNG10c6dZFLc1mwwkyOCRfz23/l0IxYF27OdyaLCRC4v1KrOstmWKdQoUw7TZUVM+5x2YhAysUcdXoYrUskpKRE4UdskSaxtYHzkgVMJbRX76G0cgEjDQKWjgjE/8mRqKVXdhbDpJ9CsIGBiBUQB0FypJYVbmZjUcGfeg9Q0Zgy4TXByh3vdew3t7/4qq8NNrYBZfmpX8gV11FsUN/9bvGhfdDZXvRZOivDsgY3Nvpuel96Rsr0joYv1BXgH3Z3+wtDyHfsNtwFMicbNzW9/HAzEcyPnpKEvObVjZ36DK1+HzcdPGBGDKJ/akvvGo8UKuZCuBravdmuIPbK+41Zjr/6WAOuqs141YHjzIcTsaFnvlDNVvvauIwEIrRL6bUH030HuxMOzJk9Gj6Qe0OFcLof/6eYmXwj3Wd3ZQtk6SP7RCIKESU22pVMPps92r6c3hnoraeEUs4DmP+fHDWNzMTd3EODFfAf2EKaV6kwQXamz8k8bPmvLCGzsJnzLjBUwhN0+EW1QdM/QHMxAV/puWmtJlMrCaZyGfP1++KRBM2ZPoknqJc28rDopwR4vs9jLtYYFyUBDXpC7A8K+nn0X9jXpAO26BUlVGYCkOu64WSsg3PdxAepbEZ3bBxeNgKMVF8MH2yhrTzA=
    - secure: >-
        D+MjDvJLfoZFh6PCy1hQS90aZ40zscwOBBYVeBrrLLgYzm0FqyZoJ2pg6p8zz0SvjG0eF8UNpp5+HTJ1Qn5ZIXeEegbKpP/ggnDWYEFe7EcTFYPUdONjv50l8z22JyzPUmTsQdyG86v0q9rvw8RMSUf+0fyG+Y+ztFDzhTQF7x/GRbmaj1/L0asbUoW7ofZHlPaSSfmNWC+Ihp8DKCZU+wDsG6gRc/SlGrt7Y1Sry46JuZx/Y41AkjK+XjShnNXMSUjfei3g6dRuiYmSDUJjbb1FLoZUoR8yPNDbic7vQYHhMflBXcSUcf474W+VGRd+Znj2Lg9a5QUYkcxS0erJ7s2okO9a6nHoLeTQdHIez1ePOF55joWh5VlPBZOEENUeVLfPuLGJdRTnmBYuWgFvFh/JFi5WjA7G/93M6I1cW5xMpAvfF5XYUWgsXrWgf+/MNfaWx4WU/t/H72sR2gug4ZKX0RMKLDwnqetYYEOl5lgrUgd6IuHwL2nYaToUhx+y+yUTJ88LwihkTcPsvdaYiw2wO1Sy6oftK/YOy5S82mW8I8nw55iRhiBel4G/ICLTXIjOPtYxGskbjHdQvOb11w5NEXdB/hgHCyVyhMeSAN8xvsMkbRGlkoLQvWDHf3zOonP0duYSfHAQFG6MOV7qnpr0qKiKwR76QQ8mCHUCX3c=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
